Express Notes API
gavenlou/m2-0621-code-solutions pull request #31
Opened 2021-08-17 06:54 UTC by gavenlou

### GET
![image](https://user-images.githubusercontent.com/32602914/129676852-0764c221-d3a4-4c78-97fd-c3ec8228284b.png)
![image](https://user-images.githubusercontent.com/32602914/129676938-4998fadd-0d2e-4aad-b5c6-2130555bc8bd.png)
![image](https://user-images.githubusercontent.com/32602914/129677013-018d65f1-78e8-4bb2-a499-84d0f2701b06.png)
![image](https://user-images.githubusercontent.com/32602914/129677058-3a3dde29-a7ed-47d0-a8de-cc7c7c51ce90.png)
### POST
![image](https://user-images.githubusercontent.com/32602914/129677136-dec4cc3c-3da0-4975-916f-8bf633d721f4.png)
![image](https://user-images.githubusercontent.com/32602914/129677247-40ffb722-f087-4fba-be26-1149af048e04.png)
### DELETE
![image](https://user-images.githubusercontent.com/32602914/129677325-8f0101f0-c2ab-497e-a0c8-3a3aa2a99c72.png)
![image](https://user-images.githubusercontent.com/32602914/129677354-8009d779-e9a0-4c0f-8e35-5b5d302f03d9.png)
![image](https://user-images.githubusercontent.com/32602914/129677475-24be22cb-e745-4fa1-8598-83f23c8120ae.png)
### PUT
![image](https://user-images.githubusercontent.com/32602914/129677570-fa620871-0c8c-4c9c-bb0a-a4b2f5379081.png)
![image](https://user-images.githubusercontent.com/32602914/129677667-1ebdf2e1-fbc0-44d5-8080-b91e056dd949.png)
![image](https://user-images.githubusercontent.com/32602914/129677735-c67e2dd4-e201-45d3-8fce-bede67d2c4f6.png)
![image](https://user-images.githubusercontent.com/32602914/129677814-f53a1738-8749-4a49-ae31-ce0ad8a568d0.png)
![image](https://user-images.githubusercontent.com/32602914/129677892-03e974ec-1dbc-4380-8b7f-9003a6d9ba01.png)

2021-08-17 21:21 UTC, TimelikeClosure requested changes

2021-08-17 21:21 UTC, TimelikeClosure commented on express-notes-api/index.js
> +})
"Clients can GET a list of notes" looks good.

2021-08-17 21:21 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
`400 Bad Request` should also trigger on fractional `id`s.

---

![image](https://user-images.githubusercontent.com/16143771/129801347-4c5310d9-6176-495b-89ca-39984162aae1.png)

2021-08-17 21:21 UTC, TimelikeClosure commented on express-notes-api/index.js
> +})
"Clients can POST a new note" looks good.

2021-08-17 21:21 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
Like above, `400 Bad Request` should trigger any time `id` isn't a positive integer.

2021-08-17 21:21 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
Like above, `400 Bad Request` should trigger for _all_ `id`s which aren't positive integers.

2021-08-18 01:32 UTC, gavenlou commented
Changed testing for number to testing for Integer.

2021-08-18 02:10 UTC, TimelikeClosure approved these changes

2021-08-18 02:12 UTC, merged